### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by QiushiYang** [Mark12Ding/SAM2Long#5]
Thanks a lot for sharing the codes of excellent work.

I tried to run the vos_inference.py while met the error "ValueError: too many values to unpack (expected 2)" in Line-359 of tools/vos_inference.py: 
"out_obj_ids, out_mask_logits = predictor.propagate_in_video(inference_state, start_frame_idx=min(input_frame_inds), reverse=False,)"

When I debug it, it seems that the output of predictor.propagate_in_video() is a single generator and cannot be subscriptable. However, in Line-362, the out_mask_logits  is subscriptable as: "output_scores_per_object[object_id][frame_idx] = out_mask_logits[frame_idx-min(input_frame_inds)].cpu().numpy()".

**Comment by Mark12Ding** [comment]
Thanks for reaching out and trying out the code!

The issue you're experiencing is likely due to reusing a previous environment where SAM2's official code is installed. This environment might cause vos_inference.py to run SAM2's code instead of SAM2Long, leading to the mismatch in outputs.

To resolve this, I recommend creating a new environment specifically for SAM2Long and ensuring that SAM2Long's code is correctly installed in that environment. This should allow predictor.propagate_in_video to return the expected outputs.

Let me know if this helps, and feel free to reach out if you encounter further issues!

**Comment by QiushiYang** [comment]
Thank you for your reply. The issue has been resolved with the following solution: 
I commented out lines 358-360 in the vos_inference.py file, and removed the previous comments between lines 362-369. Now it works.
